name: core-aam
on:
  push:
    branches:
      - 'main'
      - debug
    paths:
      - 'common/**'
      - 'core-aam/**'
      - '.github/workflows/core-aam.yml'
  workflow_dispatch:

concurrency:
  group: gh-pages-push
  queue: max

jobs:
  update-core-aam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - run: curl https://api.specref.org
      - run: curl https://respec.org
      - run: git clone git@github.com:w3c/spec-prod.git
      - run: cd spec-prod && git checkout 26674a8578635eaba312701bcb5b196113d00670
      - run: cd spec-prod && git apply ../dont-delete.patch
      - run: cd spec-prod && npm install
      - run: ./build.sh
      - run: grep -E '^\s*This document describes' core-aam/index.html.built.html
