name: core-aam
on:
  push:
    branches:
      - 'main'
      - debug
    paths:
      - 'common/**'
      - 'core-aam/**'
      - '.github/workflows/core-aam.yml'
  workflow_dispatch:

concurrency:
  group: gh-pages-push
  queue: max

jobs:
  update-core-aam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: curl https://api.specref.org
      - run: curl https://respec.org
